### ISSUE TITLE
I want to update the readme and optimize it

### ISSUE THREAD

**Issue by shaurya2093** [ashut0sh75/Cartoon#13]
--documentation
--optimization and modifications

Label-Hacktoberfest

**Comment by ashut0sh75** [comment]
Hi @shaurya2093 We liked your enthusiasm to contribute in our project, but this issue is already is #6 has already been assigned to someone else. Unfortunately, we cannot assign you this issue. 
Remember you can always make a new issue and contribute in it.
Please star our repository if you like it.

Thank You.
